# Generated by Django 2.2 on 2023-02-02 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230202_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 19, 13, 38, 537824)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 19, 13, 38, 537888)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Bosa', max_length=10),
        ),
    ]
