# Generated by Django 2.2 on 2023-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_deposits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_profits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_withdraws',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
