# Generated by Django 2.2 on 2023-02-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_stats_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdraws',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
